import * as cdk from 'aws-cdk-lib';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as events from 'aws-cdk-lib/aws-events';
import * as eventTargets from 'aws-cdk-lib/aws-events-targets';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambdaCore from 'aws-cdk-lib/aws-lambda';
import * as lambda from 'aws-cdk-lib/aws-lambda-nodejs';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import { SqsEventSource } from 'aws-cdk-lib/aws-lambda-event-sources';
import { Construct } from 'constructs';

interface ApiStackProps extends cdk.StackProps {
  usersTable: dynamodb.Table;
  hospitalsTable: dynamodb.Table;
  affiliationsTable: dynamodb.Table;
  availabilityTable: dynamodb.Table;
  appointmentsTable: dynamodb.Table;
  waitlistTable: dynamodb.Table;
  notificationsTable: dynamodb.Table;
  medicalNotesTable: dynamodb.Table;
  reviewsTable: dynamodb.Table;
  reportsTable: dynamodb.Table;
  bucket: s3.Bucket;
}

export class ApiStack extends cdk.Stack {
  public readonly userPool: cognito.UserPool;
  public readonly userPoolClient: cognito.UserPoolClient;

  constructor(scope: Construct, id: string, props: ApiStackProps) {
    super(scope, id, props);

    // Optional deploy-time settings: `cdk deploy -c allowedOrigin=https://app.example.com -c allowPaymentSimulation=false`
    // One origin or a comma-separated list. A real list (not "*") is needed for the refresh-token cookie: the browser
    // only sends credentials to an API that names the frontend's exact origin.
    const allowedOrigin: string = this.node.tryGetContext('allowedOrigin') ?? '*';
    const allowedOrigins = allowedOrigin.split(',').map((o) => o.trim()).filter(Boolean);
    const credentialedCors = !allowedOrigins.includes('*');
    if (!credentialedCors) {
      cdk.Annotations.of(this).addWarning(
        'allowedOrigin is "*": the refresh-token cookie cannot work, so sessions end after an hour. Deploy with -c allowedOrigin=https://your-frontend'
      );
    }
    const allowPaymentSimulation = String(this.node.tryGetContext('allowPaymentSimulation') ?? 'true');
    // Where the frontend is served; the doctor invitation email links to it. `-c appUrl=https://app.example.com`
    const appUrl: string = String(this.node.tryGetContext('appUrl') ?? 'http://localhost:5173').replace(/\/+$/, '');
    if (!/^https?:\/\/[^\s#?]+$/.test(appUrl)) throw new Error(`appUrl must be an http(s) URL without a query or fragment, got "${appUrl}"`);

    if (this.node.tryGetContext('appUrl') === undefined) {
      cdk.Annotations.of(this).addWarning(
        `appUrl is not set: doctor invitation links will point to ${appUrl}. Deploy with -c appUrl=<where the frontend is hosted>.`
      );
    }

    if (!process.env.SES_FROM_ADDRESS) {
      cdk.Annotations.of(this).addWarning(
        'SES_FROM_ADDRESS is not set: emails will use no-reply@example.com and SES will reject them. Set it to a verified SES identity.'
      );
    }

    // Every Lambda gets sane limits, a retained-for-a-month log group and the CORS origin.
    const createFunction = (
      fnId: string,
      entry: string,
      environment: Record<string, string> = {},
      opts: { timeoutSeconds?: number } = {}
    ) =>
      new lambda.NodejsFunction(this, fnId, {
        entry: `lambda/${entry}.ts`,
        environment: { ALLOWED_ORIGIN: allowedOrigin, ...environment },
        timeout: cdk.Duration.seconds(opts.timeoutSeconds ?? 10),
        memorySize: 256,
        architecture: lambdaCore.Architecture.ARM_64,
        logGroup: new logs.LogGroup(this, `${fnId}Logs`, {
          retention: logs.RetentionDays.ONE_MONTH,
          removalPolicy: cdk.RemovalPolicy.DESTROY,
        }),
        bundling: { minify: true, sourceMap: false },
      });

    this.userPool = new cognito.UserPool(this, 'MediCueUserPool', {
      selfSignUpEnabled: true,
      signInAliases: { email: true },
      autoVerify: { email: true },
      accountRecovery: cognito.AccountRecovery.EMAIL_ONLY,
      passwordPolicy: { minLength: 8, requireLowercase: true, requireUppercase: true, requireDigits: true },
      // Sent to doctors, staff and patients whose account somebody else created. The link opens the app with the email and the temporary
      // password filled in (in the URL fragment, which browsers never send to a server); the doctor only
      // chooses a new password (POST /auth/login -> POST /auth/new-password). The password is generated by
      // lambda/lib/accounts.ts from letters and digits, so it needs no URL escaping.
      userInvitation: {
        emailSubject: 'Your MediCue account',
        emailBody:
          'An account was created for you on MediCue.\n\n' +
          'Open this link to finish setting up your account. You only need to choose a new password:\n' +
          `${appUrl}/#/first-login?email={username}&tp={####}\n\n` +
          'If the link does not work, open MediCue and sign in with your email address ({username}) and this ' +
          'temporary password: {####}. You will be asked to choose a new password at your first login.',
      },
    });

    this.userPoolClient = new cognito.UserPoolClient(this, 'MediCueUserPoolClient', {
      userPool: this.userPool,
      authFlows: { userPassword: true },
      preventUserExistenceErrors: true,
    });

    const authorizer = new apigateway.CognitoUserPoolsAuthorizer(this, 'MediCueAuthorizer', {
      cognitoUserPools: [this.userPool],
    });

    const cognitoAuth = {
      authorizer,
      authorizationType: apigateway.AuthorizationType.COGNITO,
    };

    const T = {
      users: props.usersTable.tableName,
      hospitals: props.hospitalsTable.tableName,
      affiliations: props.affiliationsTable.tableName,
      availability: props.availabilityTable.tableName,
      appointments: props.appointmentsTable.tableName,
      waitlist: props.waitlistTable.tableName,
      notifications: props.notificationsTable.tableName,
      medicalNotes: props.medicalNotesTable.tableName,
      reviews: props.reviewsTable.tableName,
      reports: props.reportsTable.tableName,
    };

    // ---------- Events and Notifications Layer ----------
    const eventBus = new events.EventBus(this, 'MediCueEventBus');

    const notificationDLQ = new sqs.Queue(this, 'NotificationDLQ', {
      retentionPeriod: cdk.Duration.days(14),
    });
    const notificationQueue = new sqs.Queue(this, 'NotificationQueue', {
      visibilityTimeout: cdk.Duration.seconds(120),
      deadLetterQueue: { queue: notificationDLQ, maxReceiveCount: 3 },
    });

    new events.Rule(this, 'NotificationRoutingRule', {
      eventBus,
      eventPattern: { source: ['medicue.notifications'] },
      targets: [new eventTargets.SqsQueue(notificationQueue)],
    });

    new cloudwatch.Alarm(this, 'NotificationDlqAlarm', {
      alarmDescription: 'Notifications failed delivery 3 times and landed in the DLQ',
      metric: notificationDLQ.metricApproximateNumberOfMessagesVisible({ period: cdk.Duration.minutes(5) }),
      threshold: 1,
      evaluationPeriods: 1,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
    });

    // Credentials of the third-party SMS service (Twilio). CDK creates the secret with a generated placeholder
    // `authToken` and empty `accountSid` / `from`; while those are empty SMS keeps going out through SNS. Put the real
    // values in with:
    //   aws secretsmanager put-secret-value --secret-id medicue/sms-provider     //     --secret-string '{"provider":"twilio","accountSid":"AC...","authToken":"...","from":"+1..."}'
    // CDK never overwrites them afterwards, and only the notification worker may read the secret.
    const smsProviderSecret = new secretsmanager.Secret(this, 'SmsProviderSecret', {
      secretName: 'medicue/sms-provider',
      description: 'Credentials of the third-party SMS service used by the notification worker',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ provider: 'twilio', accountSid: '', from: '' }),
        generateStringKey: 'authToken',
        excludePunctuation: true,
        passwordLength: 32,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const notificationWorkerFunction = createFunction(
      'NotificationWorkerFunction',
      'notification-worker',
      {
        USERS_TABLE_NAME: T.users,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        SES_FROM_ADDRESS: process.env.SES_FROM_ADDRESS || 'no-reply@example.com',
        SMS_SECRET_ARN: smsProviderSecret.secretArn, // the credentials themselves are read from Secrets Manager at run time
      },
      { timeoutSeconds: 20 }
    );
    smsProviderSecret.grantRead(notificationWorkerFunction);
    props.usersTable.grantReadData(notificationWorkerFunction);
    props.notificationsTable.grantReadWriteData(notificationWorkerFunction);
    notificationWorkerFunction.addEventSource(new SqsEventSource(notificationQueue, { batchSize: 1 }));
    notificationWorkerFunction.addToRolePolicy(
      new iam.PolicyStatement({ actions: ['ses:SendEmail', 'ses:SendRawEmail'], resources: ['*'] })
    );
    notificationWorkerFunction.addToRolePolicy(
      new iam.PolicyStatement({ actions: ['sns:Publish'], resources: ['*'] })
    );

    // ---------- Scheduled jobs: one Lambda, one EventBridge rule per job ----------
    // Reminders (email hourly, SMS every 5 minutes), expiry of payment holds and waitlist offers (every minute) and
    // confirmed sessions nobody checked the patient in for, which become MISSED (every 15 minutes).
    const scheduledJobsFunction = createFunction(
      'ScheduledJobsFunction',
      'scheduled-jobs',
      {
        APPOINTMENTS_TABLE_NAME: T.appointments,
        AVAILABILITY_TABLE_NAME: T.availability,
        WAITLIST_TABLE_NAME: T.waitlist,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        EVENT_BUS_NAME: eventBus.eventBusName,
      },
      { timeoutSeconds: 60 }
    );
    props.appointmentsTable.grantReadWriteData(scheduledJobsFunction);
    props.availabilityTable.grantReadWriteData(scheduledJobsFunction);
    props.waitlistTable.grantReadWriteData(scheduledJobsFunction);
    props.notificationsTable.grantWriteData(scheduledJobsFunction);
    eventBus.grantPutEventsTo(scheduledJobsFunction);

    const schedule = (ruleId: string, job: string, every: cdk.Duration) =>
      new events.Rule(this, ruleId, {
        schedule: events.Schedule.rate(every),
        targets: [
          new eventTargets.LambdaFunction(scheduledJobsFunction, { event: events.RuleTargetInput.fromObject({ job }) }),
        ],
      });
    schedule('EmailReminderScheduleRule', 'email-reminders', cdk.Duration.hours(1));
    schedule('SmsReminderScheduleRule', 'sms-reminders', cdk.Duration.minutes(5));
    schedule('PaymentHoldExpiryScheduleRule', 'release-payment-holds', cdk.Duration.minutes(1));
    schedule('WaitlistOfferExpiryScheduleRule', 'release-waitlist-offers', cdk.Duration.minutes(1));
    schedule('MissedAppointmentScheduleRule', 'mark-missed', cdk.Duration.minutes(15));

    // ---------- Auth: signup, sign-in, session cookie and password recovery (all public routes) ----------
    // Key that encrypts the session cookie (see lambda/lib/cookie-seal.ts). CDK generates it once and never overwrites it;
    // to rotate, put the old value in `previousKey` and a new one in `key`, or replace `key` alone to sign everyone out.
    const cookieKeySecret = new secretsmanager.Secret(this, 'CookieKeySecret', {
      secretName: 'medicue/cookie-key',
      description: 'Encrypts the refresh-token session cookie',
      generateSecretString: { secretStringTemplate: '{}', generateStringKey: 'key', excludePunctuation: true, passwordLength: 64 },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const authFunction = createFunction('AuthFunction', 'auth', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
      // Lets accounts that still have a raw password sign in once and move to the hashed one (see lambda/login.ts).
      ALLOW_LEGACY_LOGIN: String(this.node.tryGetContext('allowLegacyLogin') ?? 'true'),
      COOKIE_SECRET_ARN: cookieKeySecret.secretArn,
    });
    props.usersTable.grantWriteData(authFunction);
    this.userPool.grant(authFunction, 'cognito-idp:AdminDeleteUser', 'cognito-idp:AdminSetUserPassword');
    cookieKeySecret.grantRead(authFunction);

    // ---------- Hospitals and their statistics (no medical notes access) ----------
    const hospitalsFunction = createFunction('HospitalsFunction', 'hospitals', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      APPOINTMENTS_TABLE_NAME: T.appointments,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      BUCKET_NAME: props.bucket.bucketName,
      EVENT_BUS_NAME: eventBus.eventBusName,
    });
    props.usersTable.grantReadWriteData(hospitalsFunction);
    props.hospitalsTable.grantReadWriteData(hospitalsFunction);
    props.appointmentsTable.grantReadData(hospitalsFunction);
    props.notificationsTable.grantWriteData(hospitalsFunction);
    props.bucket.grantRead(hospitalsFunction);
    props.bucket.grantPut(hospitalsFunction);
    eventBus.grantPutEventsTo(hospitalsFunction);
    this.userPool.grant(hospitalsFunction, 'cognito-idp:AdminDeleteUser');

    // ---------- Doctors, staff and bulk invitations (no medical notes access) ----------
    // Up to 50 accounts per bulk request; each needs a Cognito call, so this gets a longer timeout than the default.
    const teamFunction = createFunction(
      'TeamFunction',
      'team',
      {
        USER_POOL_ID: this.userPool.userPoolId,
        USERS_TABLE_NAME: T.users,
        HOSPITALS_TABLE_NAME: T.hospitals,
        AFFILIATIONS_TABLE_NAME: T.affiliations,
        AVAILABILITY_TABLE_NAME: T.availability,
      },
      { timeoutSeconds: 28 }
    );
    props.usersTable.grantReadWriteData(teamFunction);
    props.hospitalsTable.grantReadData(teamFunction);
    props.affiliationsTable.grantReadWriteData(teamFunction);
    props.availabilityTable.grantReadWriteData(teamFunction);
    this.userPool.grant(teamFunction, 'cognito-idp:AdminCreateUser', 'cognito-idp:AdminDeleteUser');

    // ---------- Profiles, reports, notifications and the platform admin's account directory ----------
    const usersFunction = createFunction('UsersFunction', 'users', {
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      REPORTS_TABLE_NAME: T.reports,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
    });
    props.usersTable.grantReadWriteData(usersFunction);
    props.hospitalsTable.grantReadData(usersFunction);
    props.reportsTable.grantWriteData(usersFunction);
    props.notificationsTable.grantReadData(usersFunction);
    this.userPool.grant(
      usersFunction,
      'cognito-idp:AdminDisableUser',
      'cognito-idp:AdminEnableUser',
      'cognito-idp:AdminUserGlobalSignOut'
    );

    // ---------- Permanent removal of an account or a hospital ----------
    // They cancel or free bookings, so they need the same tables and notification plumbing as cancelling an
    // appointment, plus Cognito user deletion.
    const removalsFunction = createFunction(
      'RemovalsFunction',
      'removals',
      {
        USER_POOL_ID: this.userPool.userPoolId,
        USERS_TABLE_NAME: T.users,
        HOSPITALS_TABLE_NAME: T.hospitals,
        AFFILIATIONS_TABLE_NAME: T.affiliations,
        AVAILABILITY_TABLE_NAME: T.availability,
        APPOINTMENTS_TABLE_NAME: T.appointments,
        WAITLIST_TABLE_NAME: T.waitlist,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        EVENT_BUS_NAME: eventBus.eventBusName,
      },
      { timeoutSeconds: 120 }
    );
    props.usersTable.grantReadWriteData(removalsFunction);
    props.hospitalsTable.grantReadWriteData(removalsFunction);
    props.affiliationsTable.grantReadWriteData(removalsFunction);
    props.availabilityTable.grantReadWriteData(removalsFunction);
    props.appointmentsTable.grantReadWriteData(removalsFunction);
    props.waitlistTable.grantReadWriteData(removalsFunction);
    props.notificationsTable.grantWriteData(removalsFunction);
    eventBus.grantPutEventsTo(removalsFunction);
    this.userPool.grant(removalsFunction, 'cognito-idp:AdminDeleteUser');

    // ---------- Availability (no medical notes access) ----------
    const availabilityFunction = createFunction('AvailabilityFunction', 'availability', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      AFFILIATIONS_TABLE_NAME: T.affiliations,
      AVAILABILITY_TABLE_NAME: T.availability,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
    });
    props.usersTable.grantReadData(availabilityFunction);
    props.hospitalsTable.grantReadData(availabilityFunction);
    props.affiliationsTable.grantReadData(availabilityFunction);
    props.availabilityTable.grantReadWriteData(availabilityFunction);
    props.notificationsTable.grantWriteData(availabilityFunction);
    eventBus.grantPutEventsTo(availabilityFunction);

    // ---------- Appointments: booking, payment, cancelling, rescheduling, check-in, completion, and the waitlist ----------
    const appointmentsFunction = createFunction('AppointmentsFunction', 'appointments', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      AVAILABILITY_TABLE_NAME: T.availability,
      APPOINTMENTS_TABLE_NAME: T.appointments,
      WAITLIST_TABLE_NAME: T.waitlist,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
      // The mock provider only runs while this is "true". Deploy with -c allowPaymentSimulation=false
      // once a real payment provider replaces it.
      ALLOW_PAYMENT_SIMULATION: allowPaymentSimulation,
    });
    props.usersTable.grantReadData(appointmentsFunction);
    props.hospitalsTable.grantReadData(appointmentsFunction);
    props.availabilityTable.grantReadWriteData(appointmentsFunction);
    props.appointmentsTable.grantReadWriteData(appointmentsFunction);
    props.waitlistTable.grantReadWriteData(appointmentsFunction);
    props.notificationsTable.grantWriteData(appointmentsFunction);
    eventBus.grantPutEventsTo(appointmentsFunction);

    // ---------- Reviews (no medical notes access) ----------
    const reviewsFunction = createFunction('ReviewsFunction', 'reviews', {
      USERS_TABLE_NAME: T.users,
      APPOINTMENTS_TABLE_NAME: T.appointments,
      REVIEWS_TABLE_NAME: T.reviews,
    });
    props.usersTable.grantReadData(reviewsFunction);
    props.appointmentsTable.grantReadData(reviewsFunction);
    props.reviewsTable.grantReadWriteData(reviewsFunction);

    // ---------- Medical Notes (the ONLY function with access to medicalNotesTable) ----------
    const medicalNotesFunction = createFunction('MedicalNotesFunction', 'medical-notes', {
      USERS_TABLE_NAME: T.users,
      APPOINTMENTS_TABLE_NAME: T.appointments,
      MEDICAL_NOTES_TABLE_NAME: T.medicalNotes,
    });
    props.usersTable.grantReadData(medicalNotesFunction);
    props.appointmentsTable.grantReadData(medicalNotesFunction);
    props.medicalNotesTable.grantReadWriteData(medicalNotesFunction);

    // ---------- API Gateway (REST API) ----------
    const restApi = new apigateway.RestApi(this, 'MediCueRestApi', {
      deployOptions: { stageName: 'prod', throttlingRateLimit: 50, throttlingBurstLimit: 100 },
      defaultCorsPreflightOptions: {
        allowOrigins: credentialedCors ? allowedOrigins : apigateway.Cors.ALL_ORIGINS,
        allowCredentials: credentialedCors,
        allowMethods: apigateway.Cors.ALL_METHODS,
        allowHeaders: ['Content-Type', 'Authorization'],
      },
    });

    // Gateway-generated errors (401 from the authorizer, 429 throttling, 5xx) bypass the Lambdas,
    // so they need the CORS header too or browsers hide the real status from the frontend.
    const corsErrorHeaders = {
      // a gateway response cannot echo the caller's origin, so it names the first (primary) one
      'Access-Control-Allow-Origin': `'${allowedOrigins[0]}'`,
      'Access-Control-Allow-Headers': "'Content-Type,Authorization'",
      ...(credentialedCors ? { 'Access-Control-Allow-Credentials': "'true'" } : {}),
    };
    restApi.addGatewayResponse('Default4xx', {
      type: apigateway.ResponseType.DEFAULT_4XX,
      responseHeaders: corsErrorHeaders,
    });
    restApi.addGatewayResponse('Default5xx', {
      type: apigateway.ResponseType.DEFAULT_5XX,
      responseHeaders: corsErrorHeaders,
    });

    new cloudwatch.Alarm(this, 'ApiServerErrorAlarm', {
      alarmDescription: 'The API returned 5xx responses',
      metric: restApi.metricServerError({ period: cdk.Duration.minutes(5) }),
      threshold: 5,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });

    // allowTestInvoke: false skips one extra Lambda::Permission per route (the console "Test" button), which keeps
    // this stack well below the 500 resources CloudFormation allows.
    const integrate = (fn: lambda.NodejsFunction) => new apigateway.LambdaIntegration(fn, { allowTestInvoke: false });

    // One Lambda serves every route of an area; lambda/<area>.ts picks the handler from "METHOD /path".
    const route = (
      resource: apigateway.Resource,
      part: string,
      method: 'GET' | 'POST',
      fn: lambda.NodejsFunction,
      authed = true
    ) => resource.addResource(part).addMethod(method, integrate(fn), authed ? cognitoAuth : undefined);

    const patients = restApi.root.addResource('patients');
    route(patients, 'signup', 'POST', authFunction, false);
    route(patients, 'confirm-signup', 'POST', authFunction, false);

    const auth = restApi.root.addResource('auth');
    route(auth, 'login', 'POST', authFunction, false);
    route(auth, 'refresh', 'POST', authFunction, false);
    route(auth, 'logout', 'POST', authFunction, false);
    route(auth, 'new-password', 'POST', authFunction, false);
    route(auth, 'forgot-password', 'POST', authFunction, false);
    route(auth, 'reset-password', 'POST', authFunction, false);

    const users = restApi.root.addResource('users');
    route(users, 'me', 'GET', usersFunction);
    route(users, 'update-profile', 'POST', usersFunction);
    route(users, 'report', 'POST', usersFunction);
    route(users, 'reported', 'GET', usersFunction);
    route(users, 'list', 'GET', usersFunction);
    route(users, 'suspend', 'POST', usersFunction);
    route(users, 'delete', 'POST', removalsFunction);
    route(users, 'bulk-create', 'POST', teamFunction);

    const hospitals = restApi.root.addResource('hospitals');
    route(hospitals, 'register', 'POST', hospitalsFunction, false);
    route(hospitals, 'approved', 'GET', hospitalsFunction, false);
    route(hospitals, 'review', 'POST', hospitalsFunction);
    route(hospitals, 'list', 'GET', hospitalsFunction);
    route(hospitals, 'delete', 'POST', removalsFunction);

    const doctors = restApi.root.addResource('doctors');
    route(doctors, 'add', 'POST', teamFunction);
    route(doctors, 'list', 'GET', teamFunction);
    route(doctors, 'remove', 'POST', teamFunction);

    const staff = restApi.root.addResource('staff');
    route(staff, 'add', 'POST', teamFunction);
    route(staff, 'list', 'GET', teamFunction);
    route(staff, 'remove', 'POST', teamFunction);

    route(restApi.root.addResource('stats'), 'hospital', 'GET', hospitalsFunction);

    const availability = restApi.root.addResource('availability');
    route(availability, 'propose', 'POST', availabilityFunction);
    route(availability, 'approve', 'POST', availabilityFunction);
    route(availability, 'pending', 'GET', availabilityFunction);
    route(availability, 'mine', 'GET', availabilityFunction);
    route(availability, 'hospital', 'GET', availabilityFunction);
    route(availability, 'browse', 'GET', availabilityFunction, false);

    const appointments = restApi.root.addResource('appointments');
    route(appointments, 'book', 'POST', appointmentsFunction);
    route(appointments, 'mine', 'GET', appointmentsFunction);
    route(appointments, 'pay', 'POST', appointmentsFunction);
    route(appointments, 'cancel', 'POST', appointmentsFunction);
    route(appointments, 'check-in', 'POST', appointmentsFunction);
    route(appointments, 'complete', 'POST', appointmentsFunction);
    route(appointments, 'reschedule', 'POST', appointmentsFunction);

    const waitlist = restApi.root.addResource('waitlist');
    route(waitlist, 'join', 'POST', appointmentsFunction);
    route(waitlist, 'claim', 'POST', appointmentsFunction);
    route(waitlist, 'mine', 'GET', appointmentsFunction);

    route(restApi.root.addResource('notifications'), 'mine', 'GET', usersFunction);

    const reviews = restApi.root.addResource('reviews');
    route(reviews, 'create', 'POST', reviewsFunction);
    route(reviews, 'doctor', 'GET', reviewsFunction);
    route(reviews, 'mine', 'GET', reviewsFunction);

    const medicalNotes = restApi.root.addResource('medical-notes');
    route(medicalNotes, 'record', 'POST', medicalNotesFunction);
    route(medicalNotes, 'list', 'GET', medicalNotesFunction);

    new cdk.CfnOutput(this, 'ApiUrl', { value: restApi.url });
    // Needed by scripts/create-platform-admin.ts and by the frontend.
    new cdk.CfnOutput(this, 'UserPoolId', { value: this.userPool.userPoolId });
    new cdk.CfnOutput(this, 'UserPoolClientId', { value: this.userPoolClient.userPoolClientId });
    new cdk.CfnOutput(this, 'UsersTableName', { value: props.usersTable.tableName });
  }
}
