import * as cdk from 'aws-cdk-lib';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as events from 'aws-cdk-lib/aws-events';
import * as eventTargets from 'aws-cdk-lib/aws-events-targets';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambdaCore from 'aws-cdk-lib/aws-lambda';
import * as lambda from 'aws-cdk-lib/aws-lambda-nodejs';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import { SqsEventSource } from 'aws-cdk-lib/aws-lambda-event-sources';
import { Construct } from 'constructs';

interface ApiStackProps extends cdk.StackProps {
  usersTable: dynamodb.Table;
  hospitalsTable: dynamodb.Table;
  affiliationsTable: dynamodb.Table;
  availabilityTable: dynamodb.Table;
  appointmentsTable: dynamodb.Table;
  waitlistTable: dynamodb.Table;
  notificationsTable: dynamodb.Table;
  medicalNotesTable: dynamodb.Table;
  reviewsTable: dynamodb.Table;
  reportsTable: dynamodb.Table;
  bucket: s3.Bucket;
}

export class ApiStack extends cdk.Stack {
  public readonly userPool: cognito.UserPool;
  public readonly userPoolClient: cognito.UserPoolClient;

  constructor(scope: Construct, id: string, props: ApiStackProps) {
    super(scope, id, props);

    // Optional deploy-time settings: `cdk deploy -c allowedOrigin=https://app.example.com -c allowPaymentSimulation=false`
    const allowedOrigin: string = this.node.tryGetContext('allowedOrigin') ?? '*';
    const allowPaymentSimulation = String(this.node.tryGetContext('allowPaymentSimulation') ?? 'true');
    // Where the frontend is served; the doctor invitation email links to it. `-c appUrl=https://app.example.com`
    const appUrl: string = String(this.node.tryGetContext('appUrl') ?? 'http://localhost:5173').replace(/\/+$/, '');
    if (!/^https?:\/\/[^\s#?]+$/.test(appUrl)) throw new Error(`appUrl must be an http(s) URL without a query or fragment, got "${appUrl}"`);

    if (this.node.tryGetContext('appUrl') === undefined) {
      cdk.Annotations.of(this).addWarning(
        `appUrl is not set: doctor invitation links will point to ${appUrl}. Deploy with -c appUrl=<where the frontend is hosted>.`
      );
    }

    if (!process.env.SES_FROM_ADDRESS) {
      cdk.Annotations.of(this).addWarning(
        'SES_FROM_ADDRESS is not set: emails will use no-reply@example.com and SES will reject them. Set it to a verified SES identity.'
      );
    }

    // Every Lambda gets sane limits, a retained-for-a-month log group and the CORS origin.
    const createFunction = (
      fnId: string,
      entry: string,
      environment: Record<string, string> = {},
      opts: { timeoutSeconds?: number } = {}
    ) =>
      new lambda.NodejsFunction(this, fnId, {
        entry: `lambda/${entry}.ts`,
        environment: { ALLOWED_ORIGIN: allowedOrigin, ...environment },
        timeout: cdk.Duration.seconds(opts.timeoutSeconds ?? 10),
        memorySize: 256,
        architecture: lambdaCore.Architecture.ARM_64,
        logGroup: new logs.LogGroup(this, `${fnId}Logs`, {
          retention: logs.RetentionDays.ONE_MONTH,
          removalPolicy: cdk.RemovalPolicy.DESTROY,
        }),
        bundling: { minify: true, sourceMap: false },
      });

    this.userPool = new cognito.UserPool(this, 'MediCueUserPool', {
      selfSignUpEnabled: true,
      signInAliases: { email: true },
      autoVerify: { email: true },
      accountRecovery: cognito.AccountRecovery.EMAIL_ONLY,
      passwordPolicy: { minLength: 8, requireLowercase: true, requireUppercase: true, requireDigits: true },
      // Sent to doctors, staff and patients whose account somebody else created. The link opens the app with the email and the temporary
      // password filled in (in the URL fragment, which browsers never send to a server); the doctor only
      // chooses a new password (POST /auth/login -> POST /auth/new-password). The password is generated by
      // lambda/lib/accounts.ts from letters and digits, so it needs no URL escaping.
      userInvitation: {
        emailSubject: 'Your MediCue account',
        emailBody:
          'An account was created for you on MediCue.\n\n' +
          'Open this link to finish setting up your account. You only need to choose a new password:\n' +
          `${appUrl}/#/first-login?email={username}&tp={####}\n\n` +
          'If the link does not work, open MediCue and sign in with your email address ({username}) and this ' +
          'temporary password: {####}. You will be asked to choose a new password at your first login.',
      },
    });

    this.userPoolClient = new cognito.UserPoolClient(this, 'MediCueUserPoolClient', {
      userPool: this.userPool,
      authFlows: { userPassword: true },
      preventUserExistenceErrors: true,
    });

    const authorizer = new apigateway.CognitoUserPoolsAuthorizer(this, 'MediCueAuthorizer', {
      cognitoUserPools: [this.userPool],
    });

    const cognitoAuth = {
      authorizer,
      authorizationType: apigateway.AuthorizationType.COGNITO,
    };

    const T = {
      users: props.usersTable.tableName,
      hospitals: props.hospitalsTable.tableName,
      affiliations: props.affiliationsTable.tableName,
      availability: props.availabilityTable.tableName,
      appointments: props.appointmentsTable.tableName,
      waitlist: props.waitlistTable.tableName,
      notifications: props.notificationsTable.tableName,
      medicalNotes: props.medicalNotesTable.tableName,
      reviews: props.reviewsTable.tableName,
      reports: props.reportsTable.tableName,
    };

    // ---------- Events and Notifications Layer ----------
    const eventBus = new events.EventBus(this, 'MediCueEventBus');

    const notificationDLQ = new sqs.Queue(this, 'NotificationDLQ', {
      retentionPeriod: cdk.Duration.days(14),
    });
    const notificationQueue = new sqs.Queue(this, 'NotificationQueue', {
      visibilityTimeout: cdk.Duration.seconds(120),
      deadLetterQueue: { queue: notificationDLQ, maxReceiveCount: 3 },
    });

    new events.Rule(this, 'NotificationRoutingRule', {
      eventBus,
      eventPattern: { source: ['medicue.notifications'] },
      targets: [new eventTargets.SqsQueue(notificationQueue)],
    });

    new cloudwatch.Alarm(this, 'NotificationDlqAlarm', {
      alarmDescription: 'Notifications failed delivery 3 times and landed in the DLQ',
      metric: notificationDLQ.metricApproximateNumberOfMessagesVisible({ period: cdk.Duration.minutes(5) }),
      threshold: 1,
      evaluationPeriods: 1,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
    });

    // Credentials of the third-party SMS service (Twilio). CDK creates the secret with a generated placeholder
    // `authToken` and empty `accountSid` / `from`; while those are empty SMS keeps going out through SNS. Put the real
    // values in with:
    //   aws secretsmanager put-secret-value --secret-id medicue/sms-provider     //     --secret-string '{"provider":"twilio","accountSid":"AC...","authToken":"...","from":"+1..."}'
    // CDK never overwrites them afterwards, and only the notification worker may read the secret.
    const smsProviderSecret = new secretsmanager.Secret(this, 'SmsProviderSecret', {
      secretName: 'medicue/sms-provider',
      description: 'Credentials of the third-party SMS service used by the notification worker',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ provider: 'twilio', accountSid: '', from: '' }),
        generateStringKey: 'authToken',
        excludePunctuation: true,
        passwordLength: 32,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const notificationWorkerFunction = createFunction(
      'NotificationWorkerFunction',
      'notification-worker',
      {
        USERS_TABLE_NAME: T.users,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        SES_FROM_ADDRESS: process.env.SES_FROM_ADDRESS || 'no-reply@example.com',
        SMS_SECRET_ARN: smsProviderSecret.secretArn, // the credentials themselves are read from Secrets Manager at run time
      },
      { timeoutSeconds: 20 }
    );
    smsProviderSecret.grantRead(notificationWorkerFunction);
    props.usersTable.grantReadData(notificationWorkerFunction);
    props.notificationsTable.grantReadWriteData(notificationWorkerFunction);
    notificationWorkerFunction.addEventSource(new SqsEventSource(notificationQueue, { batchSize: 1 }));
    notificationWorkerFunction.addToRolePolicy(
      new iam.PolicyStatement({ actions: ['ses:SendEmail', 'ses:SendRawEmail'], resources: ['*'] })
    );
    notificationWorkerFunction.addToRolePolicy(
      new iam.PolicyStatement({ actions: ['sns:Publish'], resources: ['*'] })
    );

    // ---------- Scheduled reminder checks ----------
    const checkEmailRemindersFunction = createFunction(
      'CheckEmailRemindersFunction',
      'check-email-reminders',
      {
        APPOINTMENTS_TABLE_NAME: T.appointments,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        EVENT_BUS_NAME: eventBus.eventBusName,
      },
      { timeoutSeconds: 60 }
    );
    props.appointmentsTable.grantReadWriteData(checkEmailRemindersFunction);
    props.notificationsTable.grantWriteData(checkEmailRemindersFunction);
    eventBus.grantPutEventsTo(checkEmailRemindersFunction);

    new events.Rule(this, 'EmailReminderScheduleRule', {
      schedule: events.Schedule.rate(cdk.Duration.hours(1)),
      targets: [new eventTargets.LambdaFunction(checkEmailRemindersFunction)],
    });

    const checkSmsRemindersFunction = createFunction(
      'CheckSmsRemindersFunction',
      'check-sms-reminders',
      {
        APPOINTMENTS_TABLE_NAME: T.appointments,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        EVENT_BUS_NAME: eventBus.eventBusName,
      },
      { timeoutSeconds: 60 }
    );
    props.appointmentsTable.grantReadWriteData(checkSmsRemindersFunction);
    props.notificationsTable.grantWriteData(checkSmsRemindersFunction);
    eventBus.grantPutEventsTo(checkSmsRemindersFunction);

    new events.Rule(this, 'SmsReminderScheduleRule', {
      schedule: events.Schedule.rate(cdk.Duration.minutes(5)),
      targets: [new eventTargets.LambdaFunction(checkSmsRemindersFunction)],
    });

    // ---------- Scheduled expiry checks ----------
    const releaseExpiredPaymentHoldsFunction = createFunction(
      'ReleaseExpiredPaymentHoldsFunction',
      'release-expired-payment-holds',
      {
        APPOINTMENTS_TABLE_NAME: T.appointments,
        AVAILABILITY_TABLE_NAME: T.availability,
        WAITLIST_TABLE_NAME: T.waitlist,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        EVENT_BUS_NAME: eventBus.eventBusName,
      },
      { timeoutSeconds: 60 }
    );
    props.appointmentsTable.grantReadWriteData(releaseExpiredPaymentHoldsFunction);
    props.availabilityTable.grantReadWriteData(releaseExpiredPaymentHoldsFunction);
    props.waitlistTable.grantReadWriteData(releaseExpiredPaymentHoldsFunction);
    props.notificationsTable.grantWriteData(releaseExpiredPaymentHoldsFunction);
    eventBus.grantPutEventsTo(releaseExpiredPaymentHoldsFunction);

    new events.Rule(this, 'PaymentHoldExpiryScheduleRule', {
      schedule: events.Schedule.rate(cdk.Duration.minutes(1)),
      targets: [new eventTargets.LambdaFunction(releaseExpiredPaymentHoldsFunction)],
    });

    const releaseExpiredWaitlistOffersFunction = createFunction(
      'ReleaseExpiredWaitlistOffersFunction',
      'release-expired-waitlist-offers',
      {
        WAITLIST_TABLE_NAME: T.waitlist,
        AVAILABILITY_TABLE_NAME: T.availability,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        EVENT_BUS_NAME: eventBus.eventBusName,
      },
      { timeoutSeconds: 60 }
    );
    props.waitlistTable.grantReadWriteData(releaseExpiredWaitlistOffersFunction);
    props.availabilityTable.grantReadWriteData(releaseExpiredWaitlistOffersFunction);
    props.notificationsTable.grantWriteData(releaseExpiredWaitlistOffersFunction);
    eventBus.grantPutEventsTo(releaseExpiredWaitlistOffersFunction);

    new events.Rule(this, 'WaitlistOfferExpiryScheduleRule', {
      schedule: events.Schedule.rate(cdk.Duration.minutes(1)),
      targets: [new eventTargets.LambdaFunction(releaseExpiredWaitlistOffersFunction)],
    });

    // ---------- Auth ----------
    const patientSignupFunction = createFunction('PatientSignupFunction', 'patient-signup', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
    });
    props.usersTable.grantWriteData(patientSignupFunction);
    this.userPool.grant(patientSignupFunction, 'cognito-idp:AdminDeleteUser');

    const confirmSignupFunction = createFunction('ConfirmSignupFunction', 'confirm-signup', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
    });

    const loginFunction = createFunction('LoginFunction', 'login', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
      USER_POOL_ID: this.userPool.userPoolId,
      // Lets accounts that still have a raw password sign in once and move to the hashed one (see lambda/login.ts).
      ALLOW_LEGACY_LOGIN: String(this.node.tryGetContext('allowLegacyLogin') ?? 'true'),
    });
    this.userPool.grant(loginFunction, 'cognito-idp:AdminSetUserPassword');

    const newPasswordFunction = createFunction('NewPasswordFunction', 'new-password', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
    });

    // ---------- Hospitals (no medical notes access) ----------
    const registerHospitalFunction = createFunction('RegisterHospitalFunction', 'register-hospital', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      BUCKET_NAME: props.bucket.bucketName,
    });
    props.usersTable.grantWriteData(registerHospitalFunction);
    props.hospitalsTable.grantWriteData(registerHospitalFunction);
    props.bucket.grantPut(registerHospitalFunction);
    this.userPool.grant(registerHospitalFunction, 'cognito-idp:AdminDeleteUser');

    const reviewHospitalFunction = createFunction('ReviewHospitalFunction', 'review-hospital', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
    });
    props.usersTable.grantReadData(reviewHospitalFunction);
    props.hospitalsTable.grantWriteData(reviewHospitalFunction);
    props.notificationsTable.grantWriteData(reviewHospitalFunction);
    eventBus.grantPutEventsTo(reviewHospitalFunction);

    const listHospitalsFunction = createFunction('ListHospitalsFunction', 'list-hospitals', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      BUCKET_NAME: props.bucket.bucketName,
    });
    props.usersTable.grantReadData(listHospitalsFunction);
    props.hospitalsTable.grantReadData(listHospitalsFunction);
    props.bucket.grantRead(listHospitalsFunction);

    const listApprovedHospitalsFunction = createFunction('ListApprovedHospitalsFunction', 'list-approved-hospitals', {
      HOSPITALS_TABLE_NAME: T.hospitals,
    });
    props.hospitalsTable.grantReadData(listApprovedHospitalsFunction);

    // ---------- Doctors (no medical notes access) ----------
    const addDoctorFunction = createFunction('AddDoctorFunction', 'add-doctor', {
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      AFFILIATIONS_TABLE_NAME: T.affiliations,
    });
    props.usersTable.grantReadWriteData(addDoctorFunction);
    props.hospitalsTable.grantReadData(addDoctorFunction);
    props.affiliationsTable.grantWriteData(addDoctorFunction);
    this.userPool.grant(addDoctorFunction, 'cognito-idp:AdminCreateUser', 'cognito-idp:AdminDeleteUser');

    // ---------- Availability ----------
    const proposeSlotFunction = createFunction('ProposeSlotFunction', 'propose-slot', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      AFFILIATIONS_TABLE_NAME: T.affiliations,
      AVAILABILITY_TABLE_NAME: T.availability,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
    });
    props.usersTable.grantReadData(proposeSlotFunction);
    props.hospitalsTable.grantReadData(proposeSlotFunction);
    props.affiliationsTable.grantReadData(proposeSlotFunction);
    props.availabilityTable.grantReadWriteData(proposeSlotFunction);
    props.notificationsTable.grantWriteData(proposeSlotFunction);
    eventBus.grantPutEventsTo(proposeSlotFunction);

    const approveSlotFunction = createFunction('ApproveSlotFunction', 'approve-slot', {
      AVAILABILITY_TABLE_NAME: T.availability,
    });
    props.availabilityTable.grantReadWriteData(approveSlotFunction);

    const pendingSlotsFunction = createFunction('PendingSlotsFunction', 'pending-slots', {
      AVAILABILITY_TABLE_NAME: T.availability,
    });
    props.availabilityTable.grantReadData(pendingSlotsFunction);

    // ---------- Booking & Payment ----------
    const browseSlotsFunction = createFunction('BrowseSlotsFunction', 'browse-slots', {
      AVAILABILITY_TABLE_NAME: T.availability,
      HOSPITALS_TABLE_NAME: T.hospitals,
    });
    props.availabilityTable.grantReadData(browseSlotsFunction);
    props.hospitalsTable.grantReadData(browseSlotsFunction);

    const bookAppointmentFunction = createFunction('BookAppointmentFunction', 'book-appointment', {
      USERS_TABLE_NAME: T.users,
      AVAILABILITY_TABLE_NAME: T.availability,
      APPOINTMENTS_TABLE_NAME: T.appointments,
    });
    props.usersTable.grantReadData(bookAppointmentFunction);
    props.availabilityTable.grantReadWriteData(bookAppointmentFunction);
    props.appointmentsTable.grantReadWriteData(bookAppointmentFunction);

    const myAppointmentsFunction = createFunction('MyAppointmentsFunction', 'my-appointments', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      APPOINTMENTS_TABLE_NAME: T.appointments,
    });
    props.usersTable.grantReadData(myAppointmentsFunction);
    props.hospitalsTable.grantReadData(myAppointmentsFunction);
    props.appointmentsTable.grantReadData(myAppointmentsFunction);

    const processPaymentFunction = createFunction('ProcessPaymentFunction', 'process-payment', {
      AVAILABILITY_TABLE_NAME: T.availability,
      APPOINTMENTS_TABLE_NAME: T.appointments,
      WAITLIST_TABLE_NAME: T.waitlist,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
      // The mock provider only runs while this is "true". Deploy with -c allowPaymentSimulation=false
      // once a real payment provider replaces it.
      ALLOW_PAYMENT_SIMULATION: allowPaymentSimulation,
    });
    props.availabilityTable.grantReadWriteData(processPaymentFunction);
    props.appointmentsTable.grantReadWriteData(processPaymentFunction);
    props.waitlistTable.grantReadWriteData(processPaymentFunction);
    props.notificationsTable.grantWriteData(processPaymentFunction);
    eventBus.grantPutEventsTo(processPaymentFunction);

    // ---------- Cancellation & Rescheduling ----------
    const cancelAppointmentFunction = createFunction('CancelAppointmentFunction', 'cancel-appointment', {
      APPOINTMENTS_TABLE_NAME: T.appointments,
      AVAILABILITY_TABLE_NAME: T.availability,
      WAITLIST_TABLE_NAME: T.waitlist,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
    });
    props.appointmentsTable.grantReadWriteData(cancelAppointmentFunction);
    props.availabilityTable.grantReadWriteData(cancelAppointmentFunction);
    props.waitlistTable.grantReadWriteData(cancelAppointmentFunction);
    props.notificationsTable.grantWriteData(cancelAppointmentFunction);
    eventBus.grantPutEventsTo(cancelAppointmentFunction);

    // A patient arrives: staff or the hospital admin check them in. The doctor completes the session afterwards.
    const checkInAppointmentFunction = createFunction('CheckInAppointmentFunction', 'check-in-appointment', {
      USERS_TABLE_NAME: T.users,
      APPOINTMENTS_TABLE_NAME: T.appointments,
    });
    props.usersTable.grantReadData(checkInAppointmentFunction);
    props.appointmentsTable.grantReadWriteData(checkInAppointmentFunction);

    const completeAppointmentFunction = createFunction('CompleteAppointmentFunction', 'complete-appointment', {
      USERS_TABLE_NAME: T.users,
      APPOINTMENTS_TABLE_NAME: T.appointments,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
    });
    props.usersTable.grantReadData(completeAppointmentFunction);
    props.appointmentsTable.grantReadWriteData(completeAppointmentFunction);
    props.notificationsTable.grantWriteData(completeAppointmentFunction);
    eventBus.grantPutEventsTo(completeAppointmentFunction);

    const rescheduleAppointmentFunction = createFunction('RescheduleAppointmentFunction', 'reschedule-appointment', {
      APPOINTMENTS_TABLE_NAME: T.appointments,
      AVAILABILITY_TABLE_NAME: T.availability,
      WAITLIST_TABLE_NAME: T.waitlist,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
    });
    props.appointmentsTable.grantReadWriteData(rescheduleAppointmentFunction);
    props.availabilityTable.grantReadWriteData(rescheduleAppointmentFunction);
    props.waitlistTable.grantReadWriteData(rescheduleAppointmentFunction);
    props.notificationsTable.grantWriteData(rescheduleAppointmentFunction);
    eventBus.grantPutEventsTo(rescheduleAppointmentFunction);

    // ---------- Waitlist ----------
    const joinWaitlistFunction = createFunction('JoinWaitlistFunction', 'join-waitlist', {
      WAITLIST_TABLE_NAME: T.waitlist,
      AVAILABILITY_TABLE_NAME: T.availability,
    });
    props.waitlistTable.grantReadWriteData(joinWaitlistFunction);
    props.availabilityTable.grantReadData(joinWaitlistFunction);

    const claimWaitlistOfferFunction = createFunction('ClaimWaitlistOfferFunction', 'claim-waitlist-offer', {
      WAITLIST_TABLE_NAME: T.waitlist,
      AVAILABILITY_TABLE_NAME: T.availability,
      APPOINTMENTS_TABLE_NAME: T.appointments,
    });
    props.waitlistTable.grantReadWriteData(claimWaitlistOfferFunction);
    props.availabilityTable.grantReadWriteData(claimWaitlistOfferFunction);
    props.appointmentsTable.grantReadWriteData(claimWaitlistOfferFunction);

    // ---------- Medical Notes (the ONLY functions with access to medicalNotesTable) ----------
    const recordMedicalNoteFunction = createFunction('RecordMedicalNoteFunction', 'record-medical-note', {
      APPOINTMENTS_TABLE_NAME: T.appointments,
      MEDICAL_NOTES_TABLE_NAME: T.medicalNotes,
    });
    props.appointmentsTable.grantReadData(recordMedicalNoteFunction);
    props.medicalNotesTable.grantWriteData(recordMedicalNoteFunction);

    const getMedicalNotesFunction = createFunction('GetMedicalNotesFunction', 'get-medical-notes', {
      USERS_TABLE_NAME: T.users,
      MEDICAL_NOTES_TABLE_NAME: T.medicalNotes,
    });
    props.usersTable.grantReadData(getMedicalNotesFunction);
    props.medicalNotesTable.grantReadData(getMedicalNotesFunction);

    // ---------- Read APIs used by the frontend ----------
    const getMeFunction = createFunction('GetMeFunction', 'get-me', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
    });
    props.usersTable.grantReadData(getMeFunction);
    props.hospitalsTable.grantReadData(getMeFunction);

    const listDoctorsFunction = createFunction('ListDoctorsFunction', 'list-doctors', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      AFFILIATIONS_TABLE_NAME: T.affiliations,
    });
    props.usersTable.grantReadData(listDoctorsFunction);
    props.hospitalsTable.grantReadData(listDoctorsFunction);
    props.affiliationsTable.grantReadData(listDoctorsFunction);

    const myWaitlistFunction = createFunction('MyWaitlistFunction', 'my-waitlist', {
      WAITLIST_TABLE_NAME: T.waitlist,
    });
    props.waitlistTable.grantReadData(myWaitlistFunction);

    const myNotificationsFunction = createFunction('MyNotificationsFunction', 'my-notifications', {
      NOTIFICATIONS_TABLE_NAME: T.notifications,
    });
    props.notificationsTable.grantReadData(myNotificationsFunction);

    const doctorSlotsFunction = createFunction('DoctorSlotsFunction', 'doctor-slots', {
      USERS_TABLE_NAME: T.users,
      AVAILABILITY_TABLE_NAME: T.availability,
    });
    props.usersTable.grantReadData(doctorSlotsFunction);
    props.availabilityTable.grantReadData(doctorSlotsFunction);

    const hospitalSlotsFunction = createFunction('HospitalSlotsFunction', 'hospital-slots', {
      USERS_TABLE_NAME: T.users,
      AVAILABILITY_TABLE_NAME: T.availability,
    });
    props.usersTable.grantReadData(hospitalSlotsFunction);
    props.availabilityTable.grantReadData(hospitalSlotsFunction);

    // Confirmed sessions nobody checked the patient in for within 2 hours of ending become MISSED.
    const markMissedAppointmentsFunction = createFunction(
      'MarkMissedAppointmentsFunction',
      'mark-missed-appointments',
      {
        APPOINTMENTS_TABLE_NAME: T.appointments,
        NOTIFICATIONS_TABLE_NAME: T.notifications,
        EVENT_BUS_NAME: eventBus.eventBusName,
      },
      { timeoutSeconds: 60 }
    );
    props.appointmentsTable.grantReadWriteData(markMissedAppointmentsFunction);
    props.notificationsTable.grantWriteData(markMissedAppointmentsFunction);
    eventBus.grantPutEventsTo(markMissedAppointmentsFunction);

    new events.Rule(this, 'MissedAppointmentScheduleRule', {
      schedule: events.Schedule.rate(cdk.Duration.minutes(15)),
      targets: [new eventTargets.LambdaFunction(markMissedAppointmentsFunction)],
    });

    // ---------- Profiles, reports, reviews and removals (no medical notes access) ----------
    const updateProfileFunction = createFunction('UpdateProfileFunction', 'update-profile', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
    });
    props.usersTable.grantReadWriteData(updateProfileFunction);
    props.hospitalsTable.grantReadData(updateProfileFunction);

    const reportUserFunction = createFunction('ReportUserFunction', 'report-user', {
      USERS_TABLE_NAME: T.users,
      REPORTS_TABLE_NAME: T.reports,
    });
    props.usersTable.grantReadWriteData(reportUserFunction);
    props.reportsTable.grantWriteData(reportUserFunction);

    const reportedUsersFunction = createFunction('ReportedUsersFunction', 'reported-users', {
      USERS_TABLE_NAME: T.users,
    });
    props.usersTable.grantReadData(reportedUsersFunction);

    // Shared by the two functions that permanently remove accounts: they cancel or free bookings, so they
    // need the same tables and notification plumbing as cancel-appointment, plus Cognito user deletion.
    const removalEnv = {
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      AFFILIATIONS_TABLE_NAME: T.affiliations,
      AVAILABILITY_TABLE_NAME: T.availability,
      APPOINTMENTS_TABLE_NAME: T.appointments,
      WAITLIST_TABLE_NAME: T.waitlist,
      NOTIFICATIONS_TABLE_NAME: T.notifications,
      EVENT_BUS_NAME: eventBus.eventBusName,
    };
    const grantRemoval = (fn: lambda.NodejsFunction) => {
      props.usersTable.grantReadWriteData(fn);
      props.hospitalsTable.grantReadWriteData(fn);
      props.affiliationsTable.grantReadWriteData(fn);
      props.availabilityTable.grantReadWriteData(fn);
      props.appointmentsTable.grantReadWriteData(fn);
      props.waitlistTable.grantReadWriteData(fn);
      props.notificationsTable.grantWriteData(fn);
      eventBus.grantPutEventsTo(fn);
      this.userPool.grant(fn, 'cognito-idp:AdminDeleteUser');
    };

    const deleteUserFunction = createFunction('DeleteUserFunction', 'delete-user', removalEnv, { timeoutSeconds: 60 });
    grantRemoval(deleteUserFunction);

    const deleteHospitalFunction = createFunction('DeleteHospitalFunction', 'delete-hospital', removalEnv, {
      timeoutSeconds: 120,
    });
    grantRemoval(deleteHospitalFunction);

    const removeDoctorFunction = createFunction('RemoveDoctorFunction', 'remove-doctor', {
      USERS_TABLE_NAME: T.users,
      AFFILIATIONS_TABLE_NAME: T.affiliations,
      AVAILABILITY_TABLE_NAME: T.availability,
    });
    props.usersTable.grantReadData(removeDoctorFunction);
    props.affiliationsTable.grantReadWriteData(removeDoctorFunction);
    props.availabilityTable.grantReadWriteData(removeDoctorFunction);

    const createReviewFunction = createFunction('CreateReviewFunction', 'create-review', {
      USERS_TABLE_NAME: T.users,
      APPOINTMENTS_TABLE_NAME: T.appointments,
      REVIEWS_TABLE_NAME: T.reviews,
    });
    props.usersTable.grantReadData(createReviewFunction);
    props.appointmentsTable.grantReadData(createReviewFunction);
    props.reviewsTable.grantWriteData(createReviewFunction);

    const doctorReviewsFunction = createFunction('DoctorReviewsFunction', 'doctor-reviews', {
      USERS_TABLE_NAME: T.users,
      REVIEWS_TABLE_NAME: T.reviews,
    });
    props.usersTable.grantReadData(doctorReviewsFunction);
    props.reviewsTable.grantReadData(doctorReviewsFunction);

    const myReviewsFunction = createFunction('MyReviewsFunction', 'my-reviews', {
      USERS_TABLE_NAME: T.users,
      REVIEWS_TABLE_NAME: T.reviews,
    });
    props.usersTable.grantReadData(myReviewsFunction);
    props.reviewsTable.grantReadData(myReviewsFunction);

    // ---------- Staff, statistics, bulk import, user management and password recovery ----------
    const addStaffFunction = createFunction('AddStaffFunction', 'add-staff', {
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
      AFFILIATIONS_TABLE_NAME: T.affiliations,
    });
    props.usersTable.grantReadWriteData(addStaffFunction);
    props.hospitalsTable.grantReadData(addStaffFunction);
    props.affiliationsTable.grantWriteData(addStaffFunction);
    this.userPool.grant(addStaffFunction, 'cognito-idp:AdminCreateUser', 'cognito-idp:AdminDeleteUser');

    const listStaffFunction = createFunction('ListStaffFunction', 'list-staff', { USERS_TABLE_NAME: T.users });
    props.usersTable.grantReadData(listStaffFunction);

    const removeStaffFunction = createFunction('RemoveStaffFunction', 'remove-staff', {
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
    });
    props.usersTable.grantReadWriteData(removeStaffFunction);
    this.userPool.grant(removeStaffFunction, 'cognito-idp:AdminDeleteUser');

    const hospitalStatsFunction = createFunction('HospitalStatsFunction', 'hospital-stats', {
      USERS_TABLE_NAME: T.users,
      APPOINTMENTS_TABLE_NAME: T.appointments,
    });
    props.usersTable.grantReadData(hospitalStatsFunction);
    props.appointmentsTable.grantReadData(hospitalStatsFunction);

    // Up to 50 accounts per request; each needs a Cognito call, so it gets a longer timeout than the default.
    const bulkCreateUsersFunction = createFunction(
      'BulkCreateUsersFunction',
      'bulk-create-users',
      {
        USER_POOL_ID: this.userPool.userPoolId,
        USERS_TABLE_NAME: T.users,
        HOSPITALS_TABLE_NAME: T.hospitals,
        AFFILIATIONS_TABLE_NAME: T.affiliations,
      },
      { timeoutSeconds: 28 }
    );
    props.usersTable.grantReadWriteData(bulkCreateUsersFunction);
    props.hospitalsTable.grantReadData(bulkCreateUsersFunction);
    props.affiliationsTable.grantWriteData(bulkCreateUsersFunction);
    this.userPool.grant(bulkCreateUsersFunction, 'cognito-idp:AdminCreateUser', 'cognito-idp:AdminDeleteUser');

    const listUsersFunction = createFunction('ListUsersFunction', 'list-users', {
      USERS_TABLE_NAME: T.users,
      HOSPITALS_TABLE_NAME: T.hospitals,
    });
    props.usersTable.grantReadData(listUsersFunction);
    props.hospitalsTable.grantReadData(listUsersFunction);

    const suspendUserFunction = createFunction('SuspendUserFunction', 'suspend-user', {
      USER_POOL_ID: this.userPool.userPoolId,
      USERS_TABLE_NAME: T.users,
    });
    props.usersTable.grantReadWriteData(suspendUserFunction);
    this.userPool.grant(
      suspendUserFunction,
      'cognito-idp:AdminDisableUser',
      'cognito-idp:AdminEnableUser',
      'cognito-idp:AdminUserGlobalSignOut'
    );

    const forgotPasswordFunction = createFunction('ForgotPasswordFunction', 'forgot-password', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
    });
    const resetPasswordFunction = createFunction('ResetPasswordFunction', 'reset-password', {
      USER_POOL_CLIENT_ID: this.userPoolClient.userPoolClientId,
    });

    // ---------- API Gateway (REST API) ----------
    const restApi = new apigateway.RestApi(this, 'MediCueRestApi', {
      deployOptions: { stageName: 'prod', throttlingRateLimit: 50, throttlingBurstLimit: 100 },
      defaultCorsPreflightOptions: {
        allowOrigins: allowedOrigin === '*' ? apigateway.Cors.ALL_ORIGINS : [allowedOrigin],
        allowMethods: apigateway.Cors.ALL_METHODS,
        allowHeaders: ['Content-Type', 'Authorization'],
      },
    });

    // Gateway-generated errors (401 from the authorizer, 429 throttling, 5xx) bypass the Lambdas,
    // so they need the CORS header too or browsers hide the real status from the frontend.
    const corsErrorHeaders = {
      'Access-Control-Allow-Origin': `'${allowedOrigin}'`,
      'Access-Control-Allow-Headers': "'Content-Type,Authorization'",
    };
    restApi.addGatewayResponse('Default4xx', {
      type: apigateway.ResponseType.DEFAULT_4XX,
      responseHeaders: corsErrorHeaders,
    });
    restApi.addGatewayResponse('Default5xx', {
      type: apigateway.ResponseType.DEFAULT_5XX,
      responseHeaders: corsErrorHeaders,
    });

    new cloudwatch.Alarm(this, 'ApiServerErrorAlarm', {
      alarmDescription: 'The API returned 5xx responses',
      metric: restApi.metricServerError({ period: cdk.Duration.minutes(5) }),
      threshold: 5,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });

    // allowTestInvoke: false skips one extra Lambda::Permission per route (the console "Test" button), which keeps
    // this stack well below the 500 resources CloudFormation allows.
    const integrate = (fn: lambda.NodejsFunction) => new apigateway.LambdaIntegration(fn, { allowTestInvoke: false });

    const patients = restApi.root.addResource('patients');
    patients.addResource('signup').addMethod('POST', integrate(patientSignupFunction));
    patients.addResource('confirm-signup').addMethod('POST', integrate(confirmSignupFunction));

    const auth = restApi.root.addResource('auth');
    auth.addResource('login').addMethod('POST', integrate(loginFunction));
    auth.addResource('new-password').addMethod('POST', integrate(newPasswordFunction));
    auth.addResource('forgot-password').addMethod('POST', integrate(forgotPasswordFunction));
    auth.addResource('reset-password').addMethod('POST', integrate(resetPasswordFunction));

    const users = restApi.root.addResource('users');
    users.addResource('me').addMethod('GET', integrate(getMeFunction), cognitoAuth);
    users.addResource('update-profile').addMethod('POST', integrate(updateProfileFunction), cognitoAuth);
    users.addResource('report').addMethod('POST', integrate(reportUserFunction), cognitoAuth);
    users.addResource('reported').addMethod('GET', integrate(reportedUsersFunction), cognitoAuth);
    users.addResource('delete').addMethod('POST', integrate(deleteUserFunction), cognitoAuth);
    users.addResource('list').addMethod('GET', integrate(listUsersFunction), cognitoAuth);
    users.addResource('suspend').addMethod('POST', integrate(suspendUserFunction), cognitoAuth);
    users.addResource('bulk-create').addMethod('POST', integrate(bulkCreateUsersFunction), cognitoAuth);

    const hospitals = restApi.root.addResource('hospitals');
    hospitals.addResource('register').addMethod('POST', integrate(registerHospitalFunction));
    hospitals.addResource('approved').addMethod('GET', integrate(listApprovedHospitalsFunction));
    hospitals.addResource('review').addMethod('POST', integrate(reviewHospitalFunction), cognitoAuth);
    hospitals.addResource('list').addMethod('GET', integrate(listHospitalsFunction), cognitoAuth);
    hospitals.addResource('delete').addMethod('POST', integrate(deleteHospitalFunction), cognitoAuth);

    const doctors = restApi.root.addResource('doctors');
    doctors.addResource('add').addMethod('POST', integrate(addDoctorFunction), cognitoAuth);
    doctors.addResource('list').addMethod('GET', integrate(listDoctorsFunction), cognitoAuth);
    doctors.addResource('remove').addMethod('POST', integrate(removeDoctorFunction), cognitoAuth);

    const staff = restApi.root.addResource('staff');
    staff.addResource('add').addMethod('POST', integrate(addStaffFunction), cognitoAuth);
    staff.addResource('list').addMethod('GET', integrate(listStaffFunction), cognitoAuth);
    staff.addResource('remove').addMethod('POST', integrate(removeStaffFunction), cognitoAuth);

    const stats = restApi.root.addResource('stats');
    stats.addResource('hospital').addMethod('GET', integrate(hospitalStatsFunction), cognitoAuth);

    const availability = restApi.root.addResource('availability');
    availability.addResource('propose').addMethod('POST', integrate(proposeSlotFunction), cognitoAuth);
    availability.addResource('approve').addMethod('POST', integrate(approveSlotFunction), cognitoAuth);
    availability.addResource('pending').addMethod('GET', integrate(pendingSlotsFunction), cognitoAuth);
    availability.addResource('mine').addMethod('GET', integrate(doctorSlotsFunction), cognitoAuth);
    availability.addResource('hospital').addMethod('GET', integrate(hospitalSlotsFunction), cognitoAuth);
    availability.addResource('browse').addMethod('GET', integrate(browseSlotsFunction));

    const appointments = restApi.root.addResource('appointments');
    appointments.addResource('book').addMethod('POST', integrate(bookAppointmentFunction), cognitoAuth);
    appointments.addResource('mine').addMethod('GET', integrate(myAppointmentsFunction), cognitoAuth);
    appointments.addResource('pay').addMethod('POST', integrate(processPaymentFunction), cognitoAuth);
    appointments.addResource('cancel').addMethod('POST', integrate(cancelAppointmentFunction), cognitoAuth);
    appointments.addResource('check-in').addMethod('POST', integrate(checkInAppointmentFunction), cognitoAuth);
    appointments.addResource('complete').addMethod('POST', integrate(completeAppointmentFunction), cognitoAuth);
    appointments.addResource('reschedule').addMethod('POST', integrate(rescheduleAppointmentFunction), cognitoAuth);

    const waitlist = restApi.root.addResource('waitlist');
    waitlist.addResource('join').addMethod('POST', integrate(joinWaitlistFunction), cognitoAuth);
    waitlist.addResource('claim').addMethod('POST', integrate(claimWaitlistOfferFunction), cognitoAuth);
    waitlist.addResource('mine').addMethod('GET', integrate(myWaitlistFunction), cognitoAuth);

    const notifications = restApi.root.addResource('notifications');
    notifications.addResource('mine').addMethod('GET', integrate(myNotificationsFunction), cognitoAuth);

    const reviews = restApi.root.addResource('reviews');
    reviews.addResource('create').addMethod('POST', integrate(createReviewFunction), cognitoAuth);
    reviews.addResource('doctor').addMethod('GET', integrate(doctorReviewsFunction), cognitoAuth);
    reviews.addResource('mine').addMethod('GET', integrate(myReviewsFunction), cognitoAuth);

    const medicalNotes = restApi.root.addResource('medical-notes');
    medicalNotes.addResource('record').addMethod('POST', integrate(recordMedicalNoteFunction), cognitoAuth);
    medicalNotes.addResource('list').addMethod('GET', integrate(getMedicalNotesFunction), cognitoAuth);

    new cdk.CfnOutput(this, 'ApiUrl', { value: restApi.url });
    // Needed by scripts/create-platform-admin.ts and by the frontend.
    new cdk.CfnOutput(this, 'UserPoolId', { value: this.userPool.userPoolId });
    new cdk.CfnOutput(this, 'UserPoolClientId', { value: this.userPoolClient.userPoolClientId });
    new cdk.CfnOutput(this, 'UsersTableName', { value: props.usersTable.tableName });
  }
}
